"""Visual themes: offensive (Red Team) vs defensive (Purple Team)."""

RED_OFFENSIVE = {
    "name": "offensive",
    "label": "OFFENSIVE",
    "glyph": "\u2694",  # crossed swords
    "badge_bg": "#7f1d1d",
    "badge_fg": "#fecaca",
    "badge_border": "#ef4444",
    "bg": "#0c0808",
    "surface": "#161010",
    "card": "#1a1212",
    "card_border": "#3f1515",
    "accent": "#dc2626",
    "accent_hover": "#ef4444",
    "accent_soft": "#991b1b",
    "banner": "#450a0a",
    "banner_accent": "#dc2626",
    "text": "#fef2f2",
    "muted": "#fca5a5",
    "input_bg": "#120c0c",
    "chip_bg": "#2a1515",
    "chip_fg": "#fecaca",
    "chip_border": "#7f1d1d",
    "subtitle": "Strike surface mapping  \u00b7  adversarial prompt operations",
    "mode_title": "Red Team",
    "mode_desc": "Offensive LLM testing — probe bypasses, jailbreaks, and exfil paths.",
    "btn_off_bg": "#3b0a0a",
    "btn_off_bg_active": "#7f1d1d",
    "btn_off_bg_hover": "#5c1212",
    "btn_off_border": "#ef4444",
    "btn_off_border_active": "#fca5a5",
    "btn_off_fg": "#fecaca",
    "btn_off_accent": "#dc2626",
    "btn_action_primary": "#b91c1c",
    "btn_action_primary_hover": "#dc2626",
    "btn_action_ghost": "#2a1515",
    "btn_action_ghost_hover": "#3f1515",
}

PURPLE_DEFENSIVE = {
    "name": "defensive",
    "label": "DEFENSIVE",
    "glyph": "\U0001f6e1",  # shield
    "badge_bg": "#312e81",
    "badge_fg": "#e0e7ff",
    "badge_border": "#818cf8",
    "bg": "#080812",
    "surface": "#0e0e1a",
    "card": "#12122a",
    "card_border": "#3730a3",
    "accent": "#6366f1",
    "accent_hover": "#818cf8",
    "accent_soft": "#4338ca",
    "banner": "#1e1b4b",
    "banner_accent": "#6366f1",
    "text": "#eef2ff",
    "muted": "#a5b4fc",
    "input_bg": "#0c0c18",
    "chip_bg": "#1e1b4b",
    "chip_fg": "#c7d2fe",
    "chip_border": "#4338ca",
    "subtitle": "Control validation  \u00b7  blue team collaboration and hardening",
    "mode_title": "Purple Team",
    "mode_desc": "Defensive LLM assessment — validate detections and close gaps with blue team.",
    "btn_def_bg": "#1e1b4b",
    "btn_def_bg_active": "#3730a3",
    "btn_def_bg_hover": "#2e2a6e",
    "btn_def_border": "#818cf8",
    "btn_def_border_active": "#c7d2fe",
    "btn_def_fg": "#e0e7ff",
    "btn_def_accent": "#6366f1",
    "btn_action_primary": "#4f46e5",
    "btn_action_primary_hover": "#6366f1",
    "btn_action_ghost": "#1e1b4b",
    "btn_action_ghost_hover": "#312e81",
}


def get_theme(mode: str) -> dict:
    return PURPLE_DEFENSIVE.copy() if mode == "purple" else RED_OFFENSIVE.copy()
